global_config: &global_config
  engine: TGeant4
  generator: pythia8pp
  events: 10

  o2_sim_log: sim.log                       # the file name to be used to pipe the output of each simulation into
  penalty_below : 100                        # Penalty applied if below desired minimum drop of relative ratio of hits
  hits_log_file: &hits_file hits.dat        # common name of file to pipe hit evaluation into (when using O2's analyzeHits.C macro)
  reference_dir: &reference_dir reference   # the reference directory
  baseline_dir: &baseline_dir baseline      # the baseline directory
  optimisation_dir: &opt_name optimisation  # the optimisation directory and name
  voxels_sampled_file: voxels.txt
  hashmap_file: hashmap.root
  n_voxels_x: 200
  n_voxels_y: 200
  n_voxels_z: 600
  CreateHashMapFromTxtMacroFullPath: /home/answain/alice/AliceO2MacroDev/HashMaps/CreateHashMapFromTxt.C
  CreateRadialHashMapFullPath : /home/answain/alice/AliceO2MacroDev/HashMaps/CreateRadialHashMapXY.C
  analyzeHitsFilePath : /home/answain/alice/AliceO2MacroDev/StepandHit_Analysis/analyzeHitsForOptimisation.C
  Loss_data_save_file : LossCalcData.txt

  saveNextGen : HashMaps
  zdc_skip : False #whether or not to skip the ZDC detector module (True = Skip, False = Don't Skip)

  O2DETECTORS: # all detectors we have
    - ITS
    - TOF
    - EMC
    - TRD #doesnt work in analyzeHits.C
    - PHS
    - FT0 #doesnt work in analyzeHits.C
    - HMP 
    - MFT
    - FDD
    - FV0
    - MCH
    - MID
    - CPV
    - ZDC # May be removed from most optimisations for speed-up (see zdc_skip variable above) 
    - TPC

stages_user:

  reference:
    python:
      file: reference.py
      entrypoint: reference
    config: *global_config
    cwd: *reference_dir

  baseline:
    python:
      file: reference.py
      entrypoint: baseline
    config: *global_config
    cwd: *baseline_dir
    deps:
      - reference 

  baseline_hits:
    python:
      file: reference.py
      entrypoint: baseline_hits
    config: *global_config
    cwd: *baseline_dir
    deps:
      - baseline

  next_gen:
    python:
      file: genetic.py
      entrypoint: next_gen
    config :
      <<: *global_config
      DBFilepath : genetic.db
      KeepPercent : 0.1
      mutation_rate_percentage : 0.0001
      saveBredMaps : Children
      population : 100 #need to link this to the number of trials in the genetic optimisation
      fill_percent : 0.01 
    
  
stages_optimisation:
  optimisation:
    file: inner_barrel.py
    objective: objective
    jobs: 2     # desired number of jobs
    trials: 10  # desired number of trials
    study:      # where the study is stored (only give a name and leave out "storage" key if you do not have MySQL working, it will anyway fall back to the serial run if it cannot communicate with MySQL)
      name: *opt_name
      storage: #sqlite:///opt.db
    config: 
      << : *global_config
      rel_hits_cutoff: 0.95    # desired minimum drop of relative ratio of hits  
    deps:
      - baseline_hits

  #For finding the optimal cylinder to cut away the world volume outside the magnet 
  iterate_layers_xy:
    file: layer_search.py
    objective: iterate_layers_xy
    jobs: 1    # desired number of jobs
    trials: 75  # desired number of trials
    study:      # where the study is stored (only give a name and leave out "storage" key if you do not have MySQL working, it will anyway fall back to the serial run if it cannot communicate with MySQL)
      name: iterate_layers_xy
      #storage: sqlite:///opt.db
      sampler:
        name: grid
        args:
          # we assume nX == nY
          search_space: &search_space
            i_layer_xy: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 ,27 ,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99]
    config:
      <<: *global_config
      search_space: *search_space
      rel_hits_cutoff: 0.99   # desired minimum drop of relative ratio of hits   
      Rmax : 1000 #Maximum radius allowed to be chosen (chooses between 0 and Rmax)
      
    deps:
      - baseline_hits


  #For finding the optimal cylinders for ZDC/Muon detectors 
  cylinder_xy:
    file: cylinder_xy.py
    objective: cylinder_xy
    jobs: 1    # desired number of jobs
    trials: 100  # desired number of trials
    study:      # where the study is stored (only give a name and leave out "storage" key if you do not have MySQL working, it will anyway fall back to the serial run if it cannot communicate with MySQL)
      name: *opt_name
      #storage: sqlite:///opt.db
    config:
      << : *global_config
      search_space: *search_space
      rel_hits_cutoff: 0.99   # desired minimum drop of relative ratio of hits   
      Rmax : 200 #Maximum radius allowed to be chosen (chooses between 0 and Rmax)
      Zmin : -3000 # the zmin zmax basicailly tell the optimiser where to look to optimise
      Zmax : -1800 #
    deps:
      - baseline_hits

  #Takes a set of cylinders from a CSV file and tries to optimise further
  fine_tuning_cylinders:
    file: fine_tuning.py
    objective: fine_tuning_cylinders
    jobs: 3    # desired number of jobs
    trials: 100  # desired number of trials
    study:      # where the study is stored (only give a name and leave out "storage" key if you do not have MySQL working, it will anyway fall back to the serial run if it cannot communicate with MySQL)
      name: *opt_name
      #storage: sqlite:///opt.db
    config:
      << : *global_config
      search_space: *search_space
      rel_hits_cutoff: 0.99   # desired minimum drop of relative ratio of hits   
      csv_filepath : #filepath to the csv folder with data about the cylinders
      ZaxisLeeway_percent: 10
      RadialLeeWay_percent: 10

      AddMapsMacroFilePath : /home/answain/alice/AliceO2MacroDev/HashMaps/AddHashMaps.C 
    deps:
      - baseline_hits


  genetic:
    file: genetic.py
    objective: genetic
    jobs: 1
    trials: 100
    config : 
      <<: *global_config
      rel_hits_cutoff: 0.95     # desired minimum drop of relative ratio of hits 
    deps:
      - next_gen
      - baseline_hits
    
    
    #study:
    #  name: genetic
    #  sampler:
    #    name: NSGAII
    #    args:
    #     population_size: 50
          #mutation_prob: 0.01
          #crossover: 
          #crossover_prob:
          #swapping_prob:


# evaluate:
#      python:
#    file: evaluate.py
#    entrypoint: evaluate
#    optimisations:
#      - optimisation
#    config: *global_config
