global_config: &global_config
  engine: TGeant4
  generator: pythia8pp
  events: 5
  o2_sim_log: sim.log                       # the file name to be used to pipe the output of each simulation into
  penalty_below : 10                      # Penalty applied if below desired minimum drop of relative ratio of hits
  hits_log_file: &hits_file hits.dat        # common name of file to pipe hit evaluation into (when using O2's analyzeHits.C macro)
  reference_dir: &reference_dir reference   # the reference directory
  baseline_dir: &baseline_dir baseline      # the baseline directory
  optimisation_dir: &opt_name optimisation  # the optimisation directory and name

  #Voxelmap info.
  n_voxels_x: 200
  n_voxels_y: 200
  n_voxels_z: 600

  #Filepath to the radial hashmap creation macro
  CreateRadialHashMapFullPath : ../../AliceO2MacroDev/HashMaps/CreateRadialHashMapXY.C

  #Filepath to the analyzeHits macro 
  analyzeHitsFilePath : ../../AliceO2MacroDev/StepandHit_Analysis/analyzeHitsForOptimisation.C
  optimisation_framework_filepath : ../optimise.py

  Loss_data_save_file : LossCalcData.txt #Where info used to calculate the loss function is saved

  txt_of_maps : maps.txt 
  
  zdc_skip : True #whether or not to skip the ZDC detector module (True = Skip, False = Don't Skip)
  
  csv_filepath_write : cylinder_data.csv #CSV filepath that gets written to that is called by the code injection


  O2DETECTORS: # all detectors we have
    - ITS
    - TOF
    - EMC
    - TRD #doesnt work in analyzeHits.C
    - PHS
    - FT0 #doesnt work in analyzeHits.C
    - HMP 
    - MFT
    - FDD
    - FV0
    - MCH
    - MID
    - CPV
    - ZDC # May be removed from most optimisations for speed-up (see zdc_skip variable above) 
    - TPC

stages_user:

  reference:
    python:
      file: ../reference.py
      entrypoint: reference
    config: *global_config
    cwd: *reference_dir

  baseline:
    python:
      file: ../reference.py
      entrypoint: baseline
    config: *global_config
    cwd: *baseline_dir
    deps:
      - reference 

  baseline_hits:
    python:
      file: ../reference.py
      entrypoint: baseline_hits
    config: *global_config
    cwd: *baseline_dir
    deps:
      - baseline  
  
stages_optimisation:

  #Takes a set of cylinders from a CSV file and tries to optimise further
  fine_tuning:
    file: fine_tuning.py
    objective: fine_tuning_cylinders
    jobs: 1    # desired number of jobs
    trials: 100  # desired number of trials
    study:      # where the study is stored (only give a name and leave out "storage" key if you do not have MySQL working, it will anyway fall back to the serial run if it cannot communicate with MySQL)
      name: *opt_name
      #storage: sqlite:///opt.db
    config:
      << : *global_config

      rel_hits_cutoff: 0.99   # desired minimum drop of relative ratio of hits   
      csv_filepath_cylinders : /home/answain/alice/TestingFolders/TestingCleanCode/FineTuning/fine_tuning.csv #filepath to the csv folder with data about the cylinders
      ZaxisLeeway_percent: 5
      RadialLeeWay_percent: 5
      NoVoxelMap : False 
      AddMapsMacroFilePath : /home/answain/alice/AliceO2MacroDev/HashMaps/AddHashMaps.C 
    deps:
      - baseline_hits

  #Sane as above but doesn't use a voxel map -> much faster. 
  fine_tuning_no_voxel_map:
    file: fine_tuning_no_voxelmap.py
    objective: fine_tuning_cylinders
    jobs: 1     # desired number of jobs
    trials: 1000  # desired number of trials
    study:      # where the study is stored (only give a name and leave out "storage" key if you do not have MySQL working, it will anyway fall back to the serial run if it cannot communicate with MySQL)
      name: *opt_name
      #storage: sqlite:///opt.db
    config:
      << : *global_config
      rel_hits_cutoff: 0.99   # desired minimum drop of relative ratio of hits   
      csv_filepath_cylinders : /home/answain/alice/TestingFolders/TestingCleanCode/FineTuning/fine_tuning.csv  #filepath to the csv folder with data about the cylinders
      NoVoxelMap : True
      ZaxisLeeway_percent: 25 #Same as below but for Z
      RadialLeeWay_percent: 50 #What leeway is given to radius guesses in the optimisations (% above / below the current value.)    
    deps:
      - baseline_hits
