global_config: &global_config
    engine: TGeant4
    generator: pythia8pp
    events: 10
    O2PASSIVE: # all passive modules there are (static)
        - HALL
        - PIPE
        - CAVE
        - MAG
        - DIPO
        - ABSO
        - SHIL
        - FRAME
        - COMP
    O2DETECTORS: # all detectors there are (static)
        - ITS
        - ALPIDE
        - TOF
        - EMC
        - TRD
        - PHS
        - FT0
        - HMP
        - MFT
        - FDD
        - FV0
        - MCH
        - MID
        - CPV
        - ZDC
        - TPC
    REPLAY_CUT_PARAMETERS: # all parameters there are (static)
        - CUTGAM
        - CUTELE
        - CUTNEU
        - CUTHAD
        - CUTMUO
        - BCUTE
        - BCUTM
        - DCUTE
        - DCUTM
        - PPCUTM
        - TOFMAX
    modules_to_optimise: # choose from O2PASSIVE
        - HALL
        - PIPE
        - CAVE
        #- MAG
        #- DIPO
        #- ABSO
        #- SHIL
        #- FRAME
        #- COMP
    parameters_to_optimise: # choose from REPLAY_CUT_PARAMETERS
        - CUTGAM
        - CUTELE
        - CUTNEU
        - CUTHAD
        - CUTMUO
        #- BCUTE
        #- BCUTM
        #- DCUTE
        #- DCUTM
        #- PPCUTM
        #- TOFMAX
    o2_medium_params_reference: o2_medium_params_reference.json # the name of the file where the O2 reference parameters will be found
    o2_sim_log: sim.log                                         # the file name to be used to pipe the output of each simulation into
    passive_medium_ids_map: passive_medium_ids_map.yaml         # YAML to serialise the mapping of medium IDs to each passive module
    detector_medium_ids_map: detector_medium_ids_map.yaml       # YAML to serialise the mapping of medium IDs to each detector
    reference_params: reference_params.yaml                     # YAML to serialise the numpy array of parameters into
    index_to_med_id: index_to_med_id.yaml                       # YAML to serialise and map each medium ID to a global ID
    rel_hits_cutoff: 0.95                                       # desired minimum drop of relative ratio of hits
    search_value_low: 0.00001                                   # the lower bound of values to be drawn for each parameter
    search_value_up: 1.                                         # the upper bound of values to be drawn for each parameter
    hits_log_file: &hits_file hits.dat                          # common name of file to pipe hit evaluation into (when using O2's analyzeHits.C macro)
    reference_dir: &reference_dir reference                     # the reference directory
    baseline_dir: &baseline_dir baseline                        # the baseline directory


stages_user:
    reference_sim: # the reference run
        python:
            file: /PATH/TO/o2tunerRecipes/transport_cut_optimisation/reference.py
            entrypoint: run_reference
        cwd: *reference_dir
        config: *global_config

    baseline_sim: # basline run to exclude any RNG effects during hit extraction
        python:
            file: /PATH/TO/o2tunerRecipes/transport_cut_optimisation/reference.py
            entrypoint: run_baseline
        cwd: *baseline_dir
        deps:
            - reference_sim
        config: *global_config

    baseline_hits: # extract hits for the baseline simulation
        cmd: "root -l -b -q ${O2_ROOT}/share/macro/analyzeHits.C"
        log_file: *hits_file
        deps:
            - baseline_sim
        cwd: *baseline_dir

stages_optimisation:
    optimisation_genetic_baseline:
        file: /PATH/TO/o2tunerRecipes/transport_cut_optimisation/optimise.py
        objective: objective_default
        jobs: 2     # desired number of jobs
        trials: 10  # desired number of trials
        sampler:    # use genetic sampler (leave that and it will use TPE as default)
            name: genetic
            args:
                population_size: 5
        study:      # where the study is stored (only give a name and leave out "storage" key if you do not have MySQL working, it will anyway fall back to the serial run if it cannot communicate with MySQL)
            name: optimisation_genetic_baseline_test
            storage: mysql://USER:PASSWORD@localhost/DATABASE
        cwd: optimisation_genetic_baseline
        config: *global_config
        deps:
            - baseline_hits


