global_config: &global_config
  engine: TGeant4
  generator: pythia8pp
  events: 5
  o2_sim_log: sim.log                       # the file name to be used to pipe the output of each simulation into
  penalty_below : 10                      # Penalty applied if below desired minimum drop of relative ratio of hits
  hits_log_file: &hits_file hits.dat        # common name of file to pipe hit evaluation into (when using O2's analyzeHits.C macro)
  reference_dir: &reference_dir reference   # the reference directory
  baseline_dir: &baseline_dir baseline      # the baseline directory
  optimisation_dir: &opt_name optimisation  # the optimisation directory and name
  
  #Filepath to the analyzeHits macro 
  analyzeHitsFilePath : /home/answain/alice/AliceO2MacroDev/StepandHit_Analysis/analyzeHitsForOptimisation.C
  
  Loss_data_save_file : LossCalcData.txt #Where info used to calculate the loss function is saved
  
  zdc_skip : True #whether or not to skip the ZDC detector module (True = Skip, False = Don't Skip)
  NoVoxelMap : True #if not using voxel maps.

  #CSV filepath that gets written to CWD of the trial that is called in O2MCApplicationBase to define the cuts.
  csv_filepath_write : cylinder_data.csv 
  
  #filepath to the csv folder with data about the cylinders that were optimised without the ZDC detector.
  csv_filepath_base_data : /home/answain/alice/TestingFolders/TestingCleanCode/AddZDC/cylinder_data.csv
  csv_filepath_ZDC_added:  /home/answain/alice/TestingFolders/TestingCleanCode/AddZDC/cylinder_data_w_ZDC.csv

  optimisation_framework_filepath : /home/answain/alice/o2tunerRecipes/ParticleSpecificMaps/optimise.py

  O2DETECTORS: # all detectors we have
    - ITS
    - TOF
    - EMC
    - TRD #doesnt work in analyzeHits.C
    - PHS
    - FT0 #doesnt work in analyzeHits.C
    - HMP 
    - MFT
    - FDD
    - FV0
    - MCH
    - MID
    - CPV
    - ZDC # May be removed from most optimisations for speed-up (see zdc_skip variable above) 
    - TPC

stages_user:

  reference:
    python:
      file: ../reference.py
      entrypoint: reference
    config: *global_config
    cwd: *reference_dir

  baseline:
    python:
      file: ../reference.py
      entrypoint: baseline
    config: *global_config
    cwd: *baseline_dir
    deps:
      - reference 

  baseline_hits:
    python:
      file: ../reference.py
      entrypoint: baseline_hits
    config: *global_config
    cwd: *baseline_dir
    deps:
      - baseline

  #Adds cylinders either side of the current set to meet the Z extent set below. 
  add_zdc_cylinders:
    python:
      file: AddZDC_dep.py
      entrypoint: add_zdc_cylinders
    config :
      <<: *global_config
      number_of_cylinders : 100
      Zextent : [-13000,13000]
      R_added : 80
    
  
stages_optimisation:
  #For adding optimisation for the ZDC detector in the simulations from a set of cylidners that was found
  #when the ZDC detector wasn't included.

  AddZDC:
    file: AddZDC.py
    objective: fine_tuning_cylinders_ZDC_only
    jobs: 1     # desired number of jobs
    trials: 200  # desired number of trials
    study:      # where the study is stored (only give a name and leave out "storage" key if you do not have MySQL working, it will anyway fall back to the serial run if it cannot communicate with MySQL)
      name: *opt_name
      #storage: sqlite:///opt.db
    config:
      << : *global_config
      rel_hits_cutoff: 0.99   # desired minimum drop of relative ratio of hits, anything below, a penalty is applied to the loss function  
      RadialLeeWay_percent: 100  #What leeway is given to radius guesses in the optimisations (% above / below the current value.)    
    deps:
      - baseline_hits
      - add_zdc_cylinders
